image: Visual Studio 2019
skip_commits:
  message: /Merge pull request.*/
build_script:
- ps: >-
    dotnet build --configuration Release

    dotnet test --configuration Release --no-build --no-restore
artifacts:
- path: nugets\**\*.nupkg